### ISSUE TITLE
Pretrained Weight

### ISSUE THREAD

**Issue by 5k5000** [ubc-vision/StableKeypoints#1]
Hello, nice work! When will you release the pre-trained models?

**Comment by 5k5000** [comment]
The learnt token

**Comment by ehedlin** [comment]
Here they are https://drive.google.com/drive/folders/1RUHfm5Lss7OkJ7hlts0jZNViVeo60rYQ?usp=sharing

**Comment by 5k5000** [comment]
Many thanks.
