### ISSUE TITLE
the sizes of different dataset

### ISSUE THREAD

**Issue by x2x5** [ubc-vision/StableKeypoints#12]
Hi, I would like to verify if the dataset sizes I printed here are correct.

It seems that for Human3.6M, the aligned and unaligned datasets have different paths. My assumption is that the aligned dataset is the one previously downloaded, while the unaligned dataset uses the original dataset with some images filtered out.

| Dataset             | Train  | Test  |
| ------------------- | ------ | ----- |
| taichi              | 5000   | 300   |
| cub_aligned         | 5964   | 2874  |
| cub_001             | 29     | 17    |
| cub_002             | 30     | 14    |
| cub_003             | 30     | 15    |
| cub_all             | 5964   | 2874  |
| deepfashion         | 10604  | 1179  |
| celeba_aligned      | 19000  | 1000  |
| celeba_wild         | 5379   | 283   |
| human3.6m           | 796648 | 87975 |
| unaligned_human3.6m | 159444 | 17615 |

Additionally, since the evaluation batch size is set to 1, would this process be very time-consuming, especially for the Human3.6M dataset?

The below are time records of my experiments:

| Dataset     | Eval Time    | Images |
| ----------- | ------------ | ------ |
| taichi      | 0.1 hours    | 300    |
| celeba      | 0.5 hours    | 1000   |
| deepfashion | 1 hour       | 1179   |
| cub         | 2 hours      | 2874   |
| human36m    | -            | 87975  |

I guess human36 evaluating will be 60 hours?

**Comment by ehedlin** [comment]
Yes, the evaluation for human3.6m was definitely time consuming. And for the unaligned human3.6m dataset I used [this repository](https://github.com/anibali/h36m-fetch) to install/process the dataset. This discards frames that are too similar. 

And I dont have the datasets downloaded anymore but those lengths look right to me.

**Comment by x2x5** [comment]
> Yes, the evaluation for human3.6m was definitely time consuming. And for the unaligned human3.6m dataset I used [this repository](https://github.com/anibali/h36m-fetch) to install/process the dataset. This discards frames that are too similar.
> 
> And I dont have the datasets downloaded anymore but those lengths look right to me.

Thank you so much!! I tried to find the file for long time and failed, your advice is very useful and important~

**Comment by Ahmaddimran** [comment]
> Hi, I would like to verify if the dataset sizes I printed here are correct.
> 
> It seems that for Human3.6M, the aligned and unaligned datasets have different paths. My assumption is that the aligned dataset is the one previously downloaded, while the unaligned dataset uses the original dataset with some images filtered out.
> 
> Dataset	Train	Test
> taichi	5000	300
> cub_aligned	5964	2874
> cub_001	29	17
> cub_002	30	14
> cub_003	30	15
> cub_all	5964	2874
> deepfashion	10604	1179
> celeba_aligned	19000	1000
> celeba_wild	5379	283
> human3.6m	796648	87975
> unaligned_human3.6m	159444	17615
> Additionally, since the evaluation batch size is set to 1, would this process be very time-consuming, especially for the Human3.6M dataset?
> 
> The below are time records of my experiments:
> 
> Dataset	Eval Time	Images
> taichi	0.1 hours	300
> celeba	0.5 hours	1000
> deepfashion	1 hour	1179
> cub	2 hours	2874
> human36m	-	87975
> I guess human36 evaluating will be 60 hours?

your workstation specs?

**Comment by ehedlin** [comment]
I used an RTX 3090.
