### ISSUE TITLE
annot.h5 for unaligned human36m dataset

### ISSUE THREAD

**Issue by x2x5** [ubc-vision/StableKeypoints#13]
Hi, thank you for your greak work~

I want to how to get the file 'annot.h5' ?

Because is necessary for unalinged human36m dataset training~

![image](https://github.com/user-attachments/assets/b71af1b8-0e81-4080-9577-8b96365f2598)

**Comment by ehedlin** [comment]
That is created from processing human3.6m with [this repo](https://github.com/anibali/h36m-fetch/tree/507e7334681a8a6c63c0b10a46449c4b99ea5a1c) at [this line](https://github.com/anibali/h36m-fetch/blob/507e7334681a8a6c63c0b10a46449c4b99ea5a1c/process_all.py#L162).

**Comment by x2x5** [comment]
> That is created from processing human3.6m with [this repo](https://github.com/anibali/h36m-fetch/tree/507e7334681a8a6c63c0b10a46449c4b99ea5a1c) at [this line](https://github.com/anibali/h36m-fetch/blob/507e7334681a8a6c63c0b10a46449c4b99ea5a1c/process_all.py#L162).

Thank you so much! I really appreciate it~
