### ISSUE TITLE
Instructions for using custom dataset

### ISSUE THREAD

**Issue by hjessmith** [ubc-vision/StableKeypoints#2]
This is such a cool idea- thank for you releasing the code. I'd like to try this with a custom dataset. Are there any instructions or steps I'll need to take to make it work?

**Comment by pablogago11** [comment]
Yes, I totally agree with @hjessmith. Thanks authors for sharing such nice/hard work. In my case, I would like to test it to detect custom 2D patterns.

**Comment by ehedlin** [comment]
Hey, sorry for the slow response. Yes you can use a custom dataset by setting the command line arguments "--dataset_name custom" and also "--dataset_loc" to the folder of images

**Comment by ehedlin** [comment]
Closing for now but feel free to re-open if needed
