### ISSUE TITLE
requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443):

### ISSUE THREAD

**Issue by tttao-uwu** [ubc-vision/StableKeypoints#3]
Thank you for your work. I want to know if you meet this error?

requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/runwayml/stable-diffusion-v1-4 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3b90aa4b50>: Failed to establish a new connection: [Errno 110] Connection timed out'))"), '(Request ID: 69c80218-3d05-4119-931c-80377840faff)')

**Comment by ehedlin** [comment]
It looks like it can't connect to the huggingface server to download the model. You can also explicitly download the model weights and set "--model_type" to be the path to the weights. This is the version used in our experiments https://huggingface.co/runwayml/stable-diffusion-v1-5

**Comment by tttao-uwu** [comment]
> It looks like it can't connect to the huggingface server to download the model. You can also explicitly download the model weights and set "--model_type" to be the path to the weights. This is the version used in our experiments https://huggingface.co/runwayml/stable-diffusion-v1-5

Does use_auth_token have an impact on downloading pre trained models?

**Comment by ehedlin** [comment]
[Here is the documentation for use_auth_token](https://huggingface.co/docs/diffusers/main/en/api/diffusion_pipeline#diffusers.DiffusionPipeline.from_pretrained.use_auth_token). It sounds like your error is when connecting so its unlikely use_auth_token is relevant.  It might also be worth trying the example setup from their page as a starter. 


```
import torch
from diffusers import StableDiffusionPipeline

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16,
    use_safetensors=True,
)

prompt = "a photo of an astronaut riding a horse on mars"
pipe.enable_attention_slicing()
image = pipe(prompt).images[0]
```

If this doesn't work did downloading the weights separately work?

**Comment by tttao-uwu** [comment]
> [Here is the documentation for use_auth_token](https://huggingface.co/docs/diffusers/main/en/api/diffusion_pipeline#diffusers.DiffusionPipeline.from_pretrained.use_auth_token). It sounds like your error is when connecting so its unlikely use_auth_token is relevant. It might also be worth trying the example setup from their page as a starter.
> 
> ```
> import torch
> from diffusers import StableDiffusionPipeline
> 
> pipe = StableDiffusionPipeline.from_pretrained(
>     "runwayml/stable-diffusion-v1-5",
>     torch_dtype=torch.float16,
>     use_safetensors=True,
> )
> 
> prompt = "a photo of an astronaut riding a horse on mars"
> pipe.enable_attention_slicing()
> image = pipe(prompt).images[0]
> ```
> 
> If this doesn't work did downloading the weights separately work?

Thank you. I have solved this problem.

**Comment by tttao-uwu** [comment]
I would like to ask if you have encountered the controller.step_store['attn']==None  issue? (in coding mian.py-line235 to  optimize.py-line269 to  optimize.py-line368 to ptp_utils.py-line234 to optimize.py-line38)

**Comment by ehedlin** [comment]
I have had this before. This object collects the attention maps during the denoising pass and it appears no attention map was saved. [This function](https://github.com/ubc-vision/StableKeypoints/blob/81f40bf1ff1aac2cc0eb99dd79aea0e9af351dd9/unsupervised_keypoints/ptp_utils.py#L472) runs a monkey patch replacing the default attention function with one that collects the maps. This is brittle and requires the correct version of Diffusers since it's looking for a specific folder structure and function name. Are you using `diffusers==0.8.0`?

I will push an assertion to check to make it more clear this is happening.

**Comment by ehedlin** [comment]
Marking as resolved. Re-open if needed
