### ISSUE TITLE
Custom Data Training and Inference

### ISSUE THREAD

**Issue by HamadYA** [ubc-vision/StableKeypoints#5]
Hi,

Thanks for your work.

Could you please provide an end-to-end training and testing guide on a custom dataset?

**Comment by ehedlin** [comment]
Would it help if I created a Google colab to apply to an arbitrary user input image?

The command for custom dataset training can be found [here](https://github.com/ubc-vision/StableKeypoints?tab=readme-ov-file#example-usage)

**Comment by HamadYA** [comment]
> Would it help if I created a Google colab to apply to an arbitrary user input image?
> 
> The command for custom dataset training can be found [here](https://github.com/ubc-vision/StableKeypoints?tab=readme-ov-file#example-usage)

Sure thanks, whatever you find suitable

**Comment by HamadYA** [comment]
> Would it help if I created a Google colab to apply to an arbitrary user input image?
> 
> The command for custom dataset training can be found [here](https://github.com/ubc-vision/StableKeypoints?tab=readme-ov-file#example-usage)

Sorry for asking, but any updates?

It would be beneficial to give an example of end-to-end training and testing guide on a custom dataset for example cars datasets or animals.

**Comment by ehedlin** [comment]
Working on a colab right now and it should be ready later today

**Comment by ehedlin** [comment]
Here is a colab I made for allowing custom image input, optimizing embedding and visualizing the keypoints at the end. The main variables to update are num_keypoints, num_optimization_steps, batch_size, and furthest_point_num_sample are separated into their own cell at the beginning. I hope this helps. 

https://colab.research.google.com/drive/1ULz-HIR9LgzXL5Lr68Cn_HV4Fn6tMlBj?usp=sharing

**Comment by HamadYA** [comment]
> Here is a colab I made for allowing custom image input, optimizing embedding and visualizing the keypoints at the end. The main variables to update are num_keypoints, num_optimization_steps, batch_size, and furthest_point_num_sample are separated into their own cell at the beginning. I hope this helps.
> 
> https://colab.research.google.com/drive/1ULz-HIR9LgzXL5Lr68Cn_HV4Fn6tMlBj?usp=sharing

Thank you very much. Sorry for disturbing you in two issues.
I will try this colab now.
I am planning to use your amazing work as a reference of mine.
I am closing this issue.

**Comment by ehedlin** [comment]
Of course, no worries at all :)
