### ISSUE TITLE
the question about function run_and_find_attn

### ISSUE THREAD

**Issue by tttao-uwu** [ubc-vision/StableKeypoints#7]
Thanks for your work and code. 
I would like to inquire why commenting out the run_and_find_attn function(ptp_utils  line 261) causes an error, as it seems that the output of the run'and_find_attn function is not being used.

**Comment by ehedlin** [comment]
[This function](https://github.com/ubc-vision/StableKeypoints/blob/12b8f92d672d59f1c10ea2dbc537b650ccdd8a41/unsupervised_keypoints/ptp_utils.py#L472C5-L472C31) monkey patches stable diffusion to the output of the cross attention in stable diffusion. [This](https://github.com/ubc-vision/StableKeypoints/blob/12b8f92d672d59f1c10ea2dbc537b650ccdd8a41/unsupervised_keypoints/ptp_utils.py#L480) becomes the new forward function and [this](https://github.com/ubc-vision/StableKeypoints/blob/12b8f92d672d59f1c10ea2dbc537b650ccdd8a41/unsupervised_keypoints/ptp_utils.py#L538) Is where the output of the cross attention is collected in the new forward function. [This](https://github.com/ubc-vision/StableKeypoints/blob/12b8f92d672d59f1c10ea2dbc537b650ccdd8a41/unsupervised_keypoints/ptp_utils.py#L555) goes through and does the replacing. When this is done even though nothing is being specifically returned by the function it is able to collect the attention maps during the forward pass.I hope that makes everything clear :)

**Comment by tttao-uwu** [comment]
> [This function](https://github.com/ubc-vision/StableKeypoints/blob/12b8f92d672d59f1c10ea2dbc537b650ccdd8a41/unsupervised_keypoints/ptp_utils.py#L472C5-L472C31) monkey patches stable diffusion to the output of the cross attention in stable diffusion. [This](https://github.com/ubc-vision/StableKeypoints/blob/12b8f92d672d59f1c10ea2dbc537b650ccdd8a41/unsupervised_keypoints/ptp_utils.py#L480) becomes the new forward function and [this](https://github.com/ubc-vision/StableKeypoints/blob/12b8f92d672d59f1c10ea2dbc537b650ccdd8a41/unsupervised_keypoints/ptp_utils.py#L538) Is where the output of the cross attention is collected in the new forward function. [This](https://github.com/ubc-vision/StableKeypoints/blob/12b8f92d672d59f1c10ea2dbc537b650ccdd8a41/unsupervised_keypoints/ptp_utils.py#L555) goes through and does the replacing. When this is done even though nothing is being specifically returned by the function it is able to collect the attention maps during the forward pass.I hope that makes everything clear :)

Thanks for your replies.

**Comment by ehedlin** [comment]
Closing for now but feel free to reopen if you have more questions
