### ISSUE TITLE
How did you get the TaiChi dataset?

### ISSUE THREAD

**Issue by euminds** [ubc-vision/StableKeypoints#8]
I follow https://github.com/AliaksandrSiarohin/video-preprocessing/tree/master
## Dowloading videos and cropping according to precomputed bounding boxes
1) Instal requirments:
```
pip install -r requirements.txt
```

2) Load youtube-dl:
```
wget https://yt-dl.org/downloads/latest/youtube-dl -O youtube-dl
chmod a+rx youtube-dl
```

3) Run script to download videos, there are 2 formats that can be used for storing videos one is .mp4 and another is folder with .png images. While .png images occupy significantly more space, the format is loss-less and have better i/o performance when training.

**Taichi**
```
python load_videos.py --metadata taichi-metadata.csv --format .mp4 --out_folder taichi --workers 8
```
select number of workers based on number of cpu avaliable. Note .png format take aproximatly 80GB.

but But I failed to download youtube-dl
--2024-07-21 17:00:31--  https://yt-dl.org/downloads/latest/youtube-dl
Resolving yt-dl.org (yt-dl.org)... 95.143.172.170, 2001:1a50:11:0:5f:8f:acaa:177
Connecting to yt-dl.org (yt-dl.org)|95.143.172.170|:443... connected.
HTTP request sent, awaiting response... 451 Unavailable For Legal Reasons
2024-07-21 17:00:33 ERROR 451: Unavailable For Legal Reasons.

**Comment by ehedlin** [comment]
I have the dataset on my machine but its a very large dataset so might be difficult to transfer.

**Comment by euminds** [comment]
thanks， i got it



---Original---
From: ***@***.***&gt;
Date: Thu, Jul 25, 2024 06:07 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ubc-vision/StableKeypoints] How did you get the TaiChi dataset?(Issue #8)




 
I have the dataset on my machine but its a very large dataset so might be difficult to transfer.

**Comment by x2x5** [comment]
> thanks， i got it
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Thu, Jul 25, 2024 06:07 AM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [ubc-vision/StableKeypoints] How did you get the TaiChi dataset?(Issue #8) I have the dataset on my machine but its a very large dataset so might be difficult to transfer. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

because the taichi dataset just contains 500+300 images, I found previous research that provides these images.

![image](https://github.com/user-attachments/assets/bca3f517-61c5-471b-93ca-6bc111549472)

it's here:
https://github.com/AliaksandrSiarohin/motion-cosegmentation/issues/32

![image](https://github.com/user-attachments/assets/db288a9a-bc29-429a-84f0-ff9fe072225a)

I guess the eval_images is just like 'eval_images' in the taichi.py.

I also feel there are typos here, because I read the Siarohin paper, and found they use 5000 images for training and 300 for testing, which is exactly the same number in the eval_images.tar

![image](https://github.com/user-attachments/assets/76d1924d-5cc4-4407-b4c3-58ec7e48b12a)

**Comment by Ahmaddimran** [comment]
> > thanks， i got it
> > […](#)
> > ---Original--- From: _**@**_._**> Date: Thu, Jul 25, 2024 06:07 AM To: _**@**_.**_>; Cc: _**@**_._**_**@**_.**_>; Subject: Re: [ubc-vision/StableKeypoints] How did you get the TaiChi dataset?(Issue [#8](https://github.com/ubc-vision/StableKeypoints/issues/8)) I have the dataset on my machine but its a very large dataset so might be difficult to transfer. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> because the taichi dataset just contains 500+300 images, I found previous research that provides these images.
> 
> ![image](https://github.com/user-attachments/assets/bca3f517-61c5-471b-93ca-6bc111549472)
> 
> it's here: [AliaksandrSiarohin/motion-cosegmentation#32](https://github.com/AliaksandrSiarohin/motion-cosegmentation/issues/32)
> 
> ![image](https://github.com/user-attachments/assets/db288a9a-bc29-429a-84f0-ff9fe072225a)
> 
> I guess the eval_images is just like 'eval_images' in the taichi.py.
> 
> I also feel there are typos here, because I read the Siarohin paper, and found they use 5000 images for training and 300 for testing, which is exactly the same number in the eval_images.tar
> 
> ![image](https://github.com/user-attachments/assets/76d1924d-5cc4-4407-b4c3-58ec7e48b12a)

what about landmark coordinates files? we have to generate ourselves?
